"""changed hash length to 1000

Revision ID: 3e0625e17ab8
Revises: 5d60f2d0ba6f
Create Date: 2024-07-11 17:35:41.806794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0625e17ab8'
down_revision = '5d60f2d0ba6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gmail_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'gmail_token', name='user_token_pkey')
    )
    # ### end Alembic commands ###
