"""changed hash length to 1000

Revision ID: 5d60f2d0ba6f
Revises: 
Create Date: 2024-07-11 17:30:51.632421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d60f2d0ba6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    with op.batch_alter_table('userTokens', schema=None) as batch_op:
        batch_op.alter_column('hashedEmail',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userTokens', schema=None) as batch_op:
        batch_op.alter_column('hashedEmail',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    op.create_table('user_token',
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gmail_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'gmail_token', name='user_token_pkey')
    )
    # ### end Alembic commands ###
