"""changed gmail_token to 1000

Revision ID: 72a4bdde979e
Revises: 3e0625e17ab8
Create Date: 2024-07-11 17:37:59.831525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a4bdde979e'
down_revision = '3e0625e17ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userTokens', schema=None) as batch_op:
        batch_op.alter_column('gmail_token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userTokens', schema=None) as batch_op:
        batch_op.alter_column('gmail_token',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
